# Generated by Django 3.2.4 on 2021-07-05 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TIENDAROPA', '0004_producto_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(upload_to='uploads/'),
        ),
    ]
