# Generated by Django 3.2.4 on 2021-07-05 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TIENDAROPA', '0005_alter_producto_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='imagen',
        ),
        migrations.AddField(
            model_name='producto',
            name='img',
            field=models.BinaryField(null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='mimetype',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='name',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
